### ISSUE TITLE
some modify,Pleeeeeeeeeease ....

### ISSUE THREAD

**Issue by zzenobe** [cyishere/zhouzhou-rocks#7]
1. BLOG page: 
 * when we are on a specific article page, if we insert a LINK , when we click the link , could it open the link page in a NEW PAGE ?
 *  when we are on a specific article page, can you change the style of **the division line**? we could change it into POINT POINT POINT 😊
 *

**Comment by cyishere** [comment]
@zzenobe About the changes:

1. No problem.
2. Do you mean only 3 dots or one line dots?

**Comment by zzenobe** [comment]
> @zzenobe About the changes:
> 
> 1. No problem.
> 2. Do you mean only 3 dots or one line dots?

2. line dots,please, but the distance is larger , like :  
 .      .      .      .      .       .      .      .      .      .       .      .      .      .      .       .       .      .      .      .       .      .      .      .      .       .      
[i put 6 spaces between to dots ]  xxxoo

**Comment by cyishere** [comment]
Resolved.
